### ISSUE TITLE
How can I solve following errors:

### ISSUE THREAD

**Issue by oqtanecms** [adsau59/supbot#1]
Connected to the target VM, address: '127.0.0.1:59458', transport: 'socket'
Starting ChromeDriver 2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1) on port 48838
Only local connections are allowed.
十二月 30, 2017 7:43:00 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Detected dialect: OSS
Waiting for Whatsapp web to initialize.
Program starting.
Exception in thread "main" org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='main']//div[@class='chatlist-panel-body']//div[@class='chat-title']/span[@class='emojitext ellipsify'][contains(text(),";;1")]"}
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:31.527Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.11', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_141'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.34.522940 (1a76f96f66e3ca..., userDataDir: C:\Users\Administrator\AppD...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 63.0.3239.84, webStorageEnabled: true}
Session ID: 93e1e7c2c14c577e4416d093f90eae3b
*** Element info: {Using=xpath, value=//div[@id='main']//div[@class='chatlist-panel-body']//div[@class='chat-title']/span[@class='emojitext ellipsify'][contains(text(),";;1")]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:370)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:472)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
	at in.definex.core.ChatGroup.<init>(ChatGroup.java:27)
	at in.definex.core.DatabaseManager.getGroups(DatabaseManager.java:199)
	at in.definex.core.ChatGroupsManager.loadGroups(ChatGroupsManager.java:28)
	at in.definex.core.Looper.init(Looper.java:52)
	at in.definex.core.Looper.start(Looper.java:87)
	at in.definex.Main.main(Main.java:27)
Disconnected from the target VM, address: '127.0.0.1:59458', transport: 'socket'

Process finished with exit code 1

**Comment by adam-saudagar** [comment]
easy way to fix it, make two whatsapp group and  just put ;;1 and ;;2 in the title of the whatsapp group

why?
you have to specify the id of your whatsapp chat group and what features you would like it to have (Accounts,Help,GroupConfig are core features you will have to put) in the database like for me i have kept it 1 and 2, you can keep it any string as you want, after that just put ;;<id> in the whatsapp group title (sry for the late reply) [check the screenshots](https://postimg.org/gallery/zjcv9nda/)

**Comment by kaushpra** [comment]
**I tried renaming the groups to ;;1 & ;;2. I am getting the same error:**

*** Element info: {Using=xpath, value=//div[@class='chatlist-panel-body']//div[@class='chat-title']/span[@class='emojitext ellipsify'][contains(text(),";;1")]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:370)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:472)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
	at in.definex.core.ChatGroup.<init>(ChatGroup.java:27)
	at in.definex.core.DatabaseManager.getGroups(DatabaseManager.java:198)
	at in.definex.core.ChatGroupsManager.loadGroups(ChatGroupsManager.java:28)
	at in.definex.core.Looper.init(Looper.java:53)
	at in.definex.core.Looper.start(Looper.java:88)
	at in.definex.Main.main(Main.java:27)


**How can I resolve this.**

**I am planning to automate forwarding of messages from one group to another. Later, I want to process the incoming message before forwarding it to other group.**

**Many Thanks.**

**Comment by kaushpra** [comment]
I solved this error by changing groupName in XPaths.java:

private static final String groupName = "//div[@id='side']//div[@id='pane-side']//span[@title=';;%s']";
