### ISSUE TITLE
Checker not picking up chats

### ISSUE THREAD

**Issue by kaushpra** [adsau59/supbot#2]
Hi,

To fix the error "Exception in thread "main" org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element:" occuring in ChatGroups.java at line 27:
this.chatWebElement = driver.findElement(By.xpath(XPaths.getGroupNameXPath(groupId)));.

I have changed Xpaths.java groupName variable:

private static final String groupName = "//div[@id='side']//div[@id='pane-side']//span[@title=';;%s']";

But, I have a new error now. The code does not detect any group or responds to conversations.

Logs go on an on like below snippet:
CheckInCurrentGroupAction ended
CheckOtherGroupForNewAction started
CheckOtherGroupForNewAction ended
*********** RESETTING CHECKER *************
CheckInCurrentGroupAction started
No current chat open
CheckInCurrentGroupAction ended
CheckOtherGroupForNewAction started
CheckOtherGroupForNewAction ended
*********** RESETTING CHECKER *************
CheckInCurrentGroupAction started
No current chat open
CheckInCurrentGroupAction ended
CheckOtherGroupForNewAction started
CheckOtherGroupForNewAction ended
*********** RESETTING CHECKER *************
CheckInCurrentGroupAction started
No current chat open
CheckInCurrentGroupAction ended

**My intention is to read the message, process it and forward to other group.**

Please help.

Thanks.

**Comment by adam-saudagar** [comment]
dont change the xpath, in order for the bot to detect groups, you have to add its id to the database, I have made 2 ids (1, 2) for testing purpose but u can simply add it in the database, ids can be any string, to give a group that id just put ;;<id> in the end of the group name, like suppose your group name is "Friends", then just make it "Friends;;1"

**Comment by kaushpra** [comment]
**Thanks.**

**If I am not changing the XPath, I am getting the below error:**

Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.31.488763 (092de99f48a300..., userDataDir: C:\Users\Admin\AppData\Local...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 63.0.3239.132, webStorageEnabled: true}
Session ID: 13701b60aa9a27f935921c1cb656abea
*** Element info: {Using=xpath, value=//div[@class='chatlist-panel-body']//div[@class='chat-title']/span[@class='emojitext ellipsify'][contains(text(),";;1")]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:370)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:472)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
	at in.definex.core.ChatGroup.<init>(ChatGroup.java:27)
	at in.definex.core.DatabaseManager.getGroups(DatabaseManager.java:198)
	at in.definex.core.ChatGroupsManager.loadGroups(ChatGroupsManager.java:28)
	at in.definex.core.Looper.init(Looper.java:53)
	at in.definex.core.Looper.start(Looper.java:88)
	at in.definex.Main.main(Main.java:27)


**Database Screenshot :** 
![db screenshot](https://user-images.githubusercontent.com/37775749/38095759-d7e0daac-338e-11e8-90e7-4e34fff9485c.PNG)

**Whatsapp ScreenShot :** 
![whatsapp screenshot](https://user-images.githubusercontent.com/37775749/38095814-f1543d3a-338e-11e8-9c1e-b18074f25553.PNG)

**Comment by adam-saudagar** [comment]
oh sry, turns out, whatsapp has changed whatsapp web alot since I worked on the bot, sadly all the xpaths will have to be updated, If you can please update it and send me a pull request, if not ill update it and push a new version in few days (pretty busy lately), btw the xpath u wrote should work, its just that other xpaths will have to be updated too.

**Comment by adam-saudagar** [comment]
sorry for the delay, i have fixed the xpaths and pushed it to the repo, if you get the problem again please create another issue, thanks for posting this issue :)

**Comment by kaushpra** [comment]
Thanks.

I used the below line to click on group:

driver.findElement(By.cssSelector("span[title='"+**groupOrProfileName**+"']")).click();

And the below to send message:

WebElement input = driver.findElement(By.xpath("//div[@contenteditable='true']"));
input.sendKeys(**message**+Keys.ENTER);

**Comment by adam-saudagar** [comment]
Dont do this things manually, create an action for it and at it to the action manager,  you can use SendMessageAction to send message to any group, use use this

`
actionManager.add(new SendMessageAction(actionManager, chatgroup, driver, message);
`
this will add the sendMessageAction the the que and it will get performed at soon as all the action in the que are completed,

Doing stuff manually using the driver could mess up the bot, as it could desync the information
